/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactsRouteImport } from './routes/_site/contacts'
import { Route as SiteGetFilesRouteImport } from './routes/_site/get-files'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteServicesRouteImport } from './routes/_site/services'
import { Route as SiteCatalogIndexRouteImport } from './routes/_site/catalog/index'
import { Route as SiteCatalogCategoryRouteImport } from './routes/_site/catalog/$category'
import { Route as SiteProductSlugRouteImport } from './routes/_site/product/$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactsRoute = SiteContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGetFilesRoute = SiteGetFilesRouteImport.update({
  id: '/get-files',
  path: '/get-files',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCatalogIndexRoute = SiteCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCatalogCategoryRoute = SiteCatalogCategoryRouteImport.update({
  id: '/catalog/$category',
  path: '/catalog/$category',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductSlugRoute = SiteProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contacts': typeof SiteContactsRoute
  '/get-files': typeof SiteGetFilesRoute
  '/privacy': typeof SitePrivacyRoute
  '/services': typeof SiteServicesRoute
  '/catalog/$category': typeof SiteCatalogCategoryRoute
  '/product/$slug': typeof SiteProductSlugRoute
  '/catalog/': typeof SiteCatalogIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contacts': typeof SiteContactsRoute
  '/get-files': typeof SiteGetFilesRoute
  '/privacy': typeof SitePrivacyRoute
  '/services': typeof SiteServicesRoute
  '/': typeof SiteIndexRoute
  '/catalog/$category': typeof SiteCatalogCategoryRoute
  '/product/$slug': typeof SiteProductSlugRoute
  '/catalog': typeof SiteCatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contacts': typeof SiteContactsRoute
  '/_site/get-files': typeof SiteGetFilesRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/catalog/$category': typeof SiteCatalogCategoryRoute
  '/_site/product/$slug': typeof SiteProductSlugRoute
  '/_site/catalog/': typeof SiteCatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/get-files'
    | '/privacy'
    | '/services'
    | '/catalog/$category'
    | '/product/$slug'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contacts'
    | '/get-files'
    | '/privacy'
    | '/services'
    | '/'
    | '/catalog/$category'
    | '/product/$slug'
    | '/catalog'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/contacts'
    | '/_site/get-files'
    | '/_site/privacy'
    | '/_site/services'
    | '/_site/'
    | '/_site/catalog/$category'
    | '/_site/product/$slug'
    | '/_site/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contacts': {
      id: '/_site/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof SiteContactsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/get-files': {
      id: '/_site/get-files'
      path: '/get-files'
      fullPath: '/get-files'
      preLoaderRoute: typeof SiteGetFilesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/catalog/': {
      id: '/_site/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof SiteCatalogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/catalog/$category': {
      id: '/_site/catalog/$category'
      path: '/catalog/$category'
      fullPath: '/catalog/$category'
      preLoaderRoute: typeof SiteCatalogCategoryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/product/$slug': {
      id: '/_site/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof SiteProductSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactsRoute: typeof SiteContactsRoute
  SiteGetFilesRoute: typeof SiteGetFilesRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCatalogCategoryRoute: typeof SiteCatalogCategoryRoute
  SiteProductSlugRoute: typeof SiteProductSlugRoute
  SiteCatalogIndexRoute: typeof SiteCatalogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactsRoute: SiteContactsRoute,
  SiteGetFilesRoute: SiteGetFilesRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCatalogCategoryRoute: SiteCatalogCategoryRoute,
  SiteProductSlugRoute: SiteProductSlugRoute,
  SiteCatalogIndexRoute: SiteCatalogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
